import type { Service } from '@/lib/types';

export const SERVICES: Service[] = [
    {
        slug: 'permanent-brows',
        title: 'Permanent Brows',
        shortTitle: 'Brows',
        tagline: 'Low-maintenance brows that enhance your natural beauty.',
        description: 'Permanent makeup for eyebrows is a low-maintenance cosmetic tattoo that enhances your natural brows by adding soft, long lasting color and shape. I offer various techniques to best match each client\'s desired style, skin type, and lifestyle. Nano is a fine hair-like strokes, Ombre is a soft powdery look, and Combo is a blend of both. Results gradually lighten over time and typically require maintenance every 1–5 years after initial appointments. Already had your brows done elsewhere? I\'m your girl for the job! I happily take on corrective work and touchups from other artists.',
        image: '/images/services/brows.jpg',
        heroImage: '/images/inked5.webp',
        benefits: [
            'Wake up with perfectly shaped brows every day',
            'Multiple techniques — Nano, Ombre, or Combo — tailored to your skin and style',
            'Fill in sparse or thin areas with natural, lasting color',
            'Reduce daily makeup routine by 15–20 minutes',
            'Corrective work and touchups from other artists welcome',
            'Results last 1–5 years with proper care',
        ],
        whoIsItFor: [
            'Those with naturally thin or sparse brows',
            'Anyone wanting a low-maintenance, natural look',
            'Clients with oily skin who want longer-lasting results (Ombre)',
            'Those who have had work done elsewhere and need correction',
        ],
        prepRequirements: [
            'Avoid blood thinners (aspirin, ibuprofen, fish oil) for 48 hours prior',
            'No alcohol for 24 hours before your appointment',
            'Avoid caffeine the morning of your appointment',
            'Do not wax or tint brows for one week before',
            'Come with clean skin — no makeup on the brow area',
        ],
        aftercare: [
            'Keep brows dry for 10 days',
            'Apply provided aftercare balm as directed',
            'Avoid sweating, swimming, and saunas for 2 weeks',
            'Do not pick or scratch the healing area',
            'Avoid direct sun exposure during healing',
            'Sleep on your back to avoid friction',
        ],
        pricingStart: 450,
        duration: '2–3 hours',
        healingTime: '4–6 weeks for full healing',
        touchUpIncluded: true,
        faqs: [
            { question: 'What\'s the difference between Nano, Ombre, and Combo?', answer: 'Nano creates fine hair-like strokes for the most natural look. Ombre gives you a soft, powdery, "filled-in" finish — perfect for oily skin. Combo blends both techniques for defined shape with natural detail. We\'ll discuss the best option for you during your consultation.' },
            { question: 'How long do permanent brows last?', answer: 'Results typically last 1–5 years depending on skin type, lifestyle, and aftercare. A touch-up session is included to perfect your results.' },
            { question: 'Can you fix brows done by another artist?', answer: 'Absolutely! I happily take on corrective work and touchups from other artists. We\'ll evaluate your existing work during a consultation and create a plan to achieve your ideal brows.' },
        ],
    },
    {
        slug: 'lip-blush',
        title: 'Lip Blush',
        shortTitle: 'Lip Blush',
        tagline: 'A soft, natural wash of color for effortlessly beautiful lips.',
        description: 'Natural tint lip blushing enhances your lips with a soft, sheer wash of color. Perfect for evening out tone, defining shape, and adding life to pale or uneven lips. It subtly fills in the lips for a more balanced, full look. Neutralization is available for lips with deeper tones or discoloration — it may require multiple sessions. If a bolder, full-coverage look is desired, it can be achieved with additional sessions.',
        image: '/images/services/lip-blush.jpg',
        heroImage: '/images/inked6.webp',
        benefits: [
            'Even out lip tone with a soft, natural tint',
            'Define and correct lip shape and symmetry',
            'Create the appearance of fuller lips without fillers',
            'Neutralization available for deeper tones or discoloration',
            'Buildable coverage — from sheer to bold',
            'Achieve a youthful, refreshed "just-bitten" look',
        ],
        whoIsItFor: [
            'Those wanting to enhance natural lip color',
            'Clients with uneven lip tone, pale, or discolored lips',
            'Anyone seeking a low-maintenance lip look',
            'Those wanting definition without the filler commitment',
        ],
        prepRequirements: [
            'Exfoliate and moisturize lips daily for one week prior',
            'Avoid blood thinners for 48 hours before',
            'No filler treatments for 4 weeks prior',
            'Take a prophylactic antiviral if you have a history of cold sores',
            'Avoid caffeine and alcohol 24 hours before',
        ],
        aftercare: [
            'Keep lips moisturized with provided balm',
            'Avoid spicy, salty, or acidic foods for 3 days',
            'Do not pick at peeling or flaking',
            'Avoid kissing and oral contact for 5 days',
            'Stay out of sun and avoid lip products during healing',
        ],
        pricingStart: 500,
        duration: '2.5–3 hours',
        healingTime: '5–7 weeks for final color',
        touchUpIncluded: true,
        faqs: [
            { question: 'How natural does lip blush look?', answer: 'Lip blush is designed to look like your natural lip color, just elevated. We can go as subtle or as vivid as you prefer — think "your lips but better."' },
            { question: 'What is neutralization?', answer: 'Neutralization is a technique for lips with deeper pigmentation or discoloration. It corrects the undertone before adding color, and may require multiple sessions for optimal results.' },
            { question: 'Do I need to take antivirals?', answer: 'If you have ever had a cold sore, antivirals are required starting 3 days before and continuing 3 days after. This prevents a flare-up that could affect healing and pigment retention.' },
        ],
    },
    {
        slug: 'fine-line-tattoo',
        title: 'Fine-Line Tattoo',
        shortTitle: 'Fine-Line',
        tagline: 'Effortlessly delicate and beautifully simple forever art.',
        description: 'Effortlessly delicate and beautifully simple, fineline tattoos are the perfect way to create forever art on your body. 3–5 inch designs bring the elegance through minimal detail, making them timeless little statements that feel as light as they look. Please reach out prior to booking to chat about your design.',
        image: '/images/services/fine-line.jpg',
        heroImage: '/images/inked8.webp',
        benefits: [
            'Custom-designed for your personal story',
            'Delicate, precise 3–5 inch linework',
            'Timeless designs that feel as light as they look',
            'Professional-grade pigments and sterile technique',
            'Heals beautifully with proper aftercare',
        ],
        whoIsItFor: [
            'Those wanting a delicate, meaningful tattoo',
            'First-time tattoo clients looking for a refined experience',
            'Anyone who appreciates precision and artistic intention',
            'Clients wanting elegant, minimalist body art',
        ],
        prepRequirements: [
            'Reach out before booking to discuss your design',
            'Moisturize the area for a week before',
            'Avoid alcohol and blood thinners for 24 hours',
            'Eat a meal before your appointment',
            'Wear comfortable clothing that allows access to the tattoo area',
        ],
        aftercare: [
            'Keep covered for 2–4 hours after',
            'Wash gently with mild soap',
            'Apply thin layer of aftercare ointment',
            'Avoid submerging in water for 2 weeks',
            'Stay out of direct sun — use SPF once healed',
        ],
        pricingStart: 150,
        duration: '1–2 hours',
        healingTime: '2–4 weeks',
        touchUpIncluded: false,
        faqs: [
            { question: 'How small can designs be?', answer: 'We specialize in delicate work, but there are limits to how small we can go while maintaining long-term quality. During your consultation, we\'ll discuss sizing to ensure your design ages beautifully.' },
            { question: 'Do I need to have a design ready?', answer: 'Not at all! Reach out before booking and we can collaborate on a custom design that tells your story perfectly.' },
        ],
    },
    {
        slug: 'tiny-tattoos',
        title: 'Tiny Tattoos',
        shortTitle: 'Tiny Tats',
        tagline: 'Tiny tattoos, big meaning — dainty, minimal, full of personality.',
        description: 'Choose from 1–2 inch designs that are dainty, minimal, and full of personality. Each month, I\'ll release brand new flash sheets featuring curated designs to pick from. Want something custom? Just shoot me a message before booking — I\'ve got you!',
        image: '/images/services/tiny-tattoos.jpg',
        heroImage: '/images/inked7.webp',
        benefits: [
            'Adorable 1–2 inch designs packed with personality',
            'Monthly curated flash sheets with fresh designs',
            'Custom designs available — just reach out!',
            'Perfect first tattoo experience',
            'Quick session, minimal healing',
            '$25 teenie tats on Flash Saturdays!',
        ],
        whoIsItFor: [
            'First-time tattoo clients wanting something small and sweet',
            'Anyone who loves dainty, minimal ink',
            'Those looking for a fun, affordable tattoo experience',
            'Flash Saturday fans wanting $25 teenie tats',
        ],
        prepRequirements: [
            'Browse current flash sheet or reach out for custom ideas',
            'Moisturize the area for a few days before',
            'Avoid alcohol for 24 hours',
            'Eat a meal before your appointment',
        ],
        aftercare: [
            'Keep covered for 2–4 hours after',
            'Wash gently with mild soap',
            'Apply thin layer of aftercare ointment',
            'Avoid submerging in water for 2 weeks',
            'Stay out of direct sun — use SPF once healed',
        ],
        pricingStart: 80,
        duration: '15–45 minutes',
        healingTime: '2–3 weeks',
        touchUpIncluded: false,
        faqs: [
            { question: 'What are Flash Saturdays?', answer: 'Lil Ink\'d Permanent Artistry Flash Saturdays are a monthly event — one Saturday a month, treat yourself like it\'s always Friday the 13th with $25 teenie tats! Follow us on Instagram for dates and flash sheet drops.' },
            { question: 'Can I get a custom tiny tattoo?', answer: 'Absolutely! Just shoot me a message before booking and we\'ll work together to create something perfectly you.' },
        ],
    },
    {
        slug: 'lash-enhancement',
        title: 'Lash Enhancement',
        shortTitle: 'Lash Line',
        tagline: 'Subtle definition for brighter, more expressive eyes.',
        description: 'Lash enhancement tattoo deposits pigment directly into the lash line, creating the illusion of thicker, fuller lashes without visible liner. The result is a naturally defined eye that makes your lashes appear denser at the root — like you were born with it.',
        image: '/images/services/lash-enhancement.jpg',
        heroImage: '/images/Inked_2_1724378681.webp',
        benefits: [
            'Eyes appear brighter and more defined',
            'Eliminates the need for daily eyeliner',
            'Completely natural — looks like dense lashes, not liner',
            'Waterproof and smudge-proof',
            'Quick procedure with minimal downtime',
        ],
        whoIsItFor: [
            'Those who want subtle eye definition',
            'Clients who wear eyeliner daily',
            'Anyone with sparse lashes wanting a fuller look',
            'Contact lens wearers looking for easier routines',
        ],
        prepRequirements: [
            'Remove lash extensions 3 days prior',
            'Avoid curling lashes the day of',
            'No caffeine or blood thinners',
            'Arrive with clean eyes — no eye makeup',
        ],
        aftercare: [
            'Avoid water and steam around eyes for 5 days',
            'Do not use eye makeup for 7–10 days',
            'Avoid rubbing or touching the area',
            'Skip lash curlers during healing',
        ],
        pricingStart: 350,
        duration: '1.5–2 hours',
        healingTime: '3–4 weeks',
        touchUpIncluded: true,
        faqs: [
            { question: 'Is lash enhancement the same as eyeliner tattoo?', answer: 'No — lash enhancement is more subtle. Pigment is placed between the lash hairs for a natural, "invisible liner" effect, rather than a visible liner line.' },
        ],
    },
];
